### ISSUE TITLE
Initially the Play & More Info Button is not showing icons instead some text.

### ISSUE THREAD

**Issue by Muhsin-42** [okNeeraj/netflix-gpt#40]
**Describe the bug**
Initially the Play & More Info Button is not showing icons instead some text.

**To Reproduce**
1. In the Home page
2. Do force refresh ie, CTRL + F5
3. Then for some times on the Play & more info icon an text will be shown not the icon.

**Comment by okNeeraj** [comment]
The issue was because the default behaviour of google material icon.
The issue has been resolved now.
